# Generated by Django 3.2.13 on 2023-05-21 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230520_2000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailverification',
            options={'verbose_name': 'Подтвержденный', 'verbose_name_plural': 'Подтвержденные'},
        ),
    ]
